api/urls.py
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from . import views


schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
    path('quiz-detail/<str:code>', views.quiz_detail),
    path('answer-create/<str:code>', views.answer_create),
    path('log-in', views.log_in),
    path('auth/', include('rest_framework.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    path('', include('front.urls'))
]+static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    # quiz 
    path('quiz-create/', views.quiz_create, name='quiz_create'),
    path('quiz-detail/', views.quiz_detail, name='quiz_detail'),
    path('quiz-list/', views.quiz_list, name='quiz_list'),
    path('quiz-update/<str:code>/', views.quiz_update, name='quiz_update'),
    path('quiz-detail/<str:code>/', views.quiz_detail, name='quiz_detail'),
    path('quiz-delete/<str:code>/', views.quiz_delete, name='quiz_delete'),
    # question
    path('question-create/<str:code>/', views.question_create, name='question_create'),
    path('question-detail/<str:code>/', views.question_detail, name='question_detail'),
    path('question-update/<str:code>/', views.question_update, name='question_update'),
    path('question-delete/<str:code>/', views.question_delete, name='question_delete'),
    # answer
    path('answer-list/<str:code>/', views.answer_list, name='answer_list'),
    path('answer-detail/<str:code>/', views.answer_detail, name='answer_detail'),
    path('write-excel/<str:code>/', views.write_excel, name='write_excel'),
    

    # user
    path('log-in/', views.log_in, name='log_in'),
    path('log-out/', views.log_out, name='log_out'),
]

templates/quiz/quiz_create.html
{% extends 'base.html' %}

{% block content %}

                
    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">Quiz</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                    <a class="breadcrumb-item" href="#">Quiz</a>
                    <span class="breadcrumb-item active">Yaratish</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h4>Quiz yaratish</h4>
                <div class="m-t-25" style="max-width: 700px">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="inputName" class="col-sm-2 col-form-label">Nomi</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputName" placeholder="Quiz nomini kiriting" name="name" required>
                            </div>
                            <div class="d-flex align-items-start gap-3 mt-4">
                                <button type="submit" class="btn btn-primary w-sm"  >Saqlash</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->



{% endblock %}

templates/quiz/quiz_detail.html
{% extends 'base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Quiz</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Kategoriya</a>
                <span class="breadcrumb-item active">Ro`yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Kategoriyalar ro`yxati</h4>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col"> <a href="{% url 'dashboard:answer_list' quiz.code %}"> <i style="margin-right: 20px;">Natijalar</i> <a href="{% url 'dashboard:write_excel' quiz.code %}"><i class="anticon anticon-download"></i></a> </a></th>
                                <th scope="col"><a href="{% url 'dashboard:question_create' quiz.code %}"><i class="anticon anticon-plus"> Savol qo'shish </i></a></th>
                            </tr>
                            <tr>
                                <th scope="col">Quiz</th>
                                <th scope="col">{{quiz | striptags}}</th>
                            </tr>
                            <tr>
                                <th scope="col"> Savollar </th>
                                <th scope="col"> Harakantlar </th>

                        </thead>
                        <tbody>
                            {% for question in questions %}
                            <tr>
                                <td>
                                    <b>{{forloop.counter}}. {{question.name}}</b>
                                    <ul>
                                        {% for option in question.option_set.all %}
                                        <li>
                                            {{option}} 
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded pull-right" data-toggle="modal" data-target=".bd-example-modal-lg{{forloop.counter}}">
                                        <i class="anticon anticon-edit"></i>
                                    </button>
                                    <!-- Large modal -->
                                    <div class="modal fade bd-example-modal-lg{{question.code}}">
                                        <div class="modal-dialog modal-lg">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{question.name | striptags}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <form action="{% url 'dashboard:question_update' question.code %}" method="post">
                                                    {% csrf_token %}
                                                <div class="modal-body">
                                                    <input type="text" class="form-control" value="{{question.name}}" name="name">
                                                </div>
                                                {% for option in options %}
                                                <div class="modal-body">
                                                    <input type="text" class="form-control" value="{{option.name}}" name="name">
                                                </div>
                                                {% endfor %}
                                                <button type="submit" class="btn btn-primary btn-tone" >O`zgartirish</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Small modal -->
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-delete"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm {{question.code}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{question.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{question.name}} kategoriyani o`chirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'dashboard:question_delete' question.code %}">
                                                        {% csrf_token %}
                                                    <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            {% if queryset.paginator.num_pages > 1 %}
                                <div class="pagination-area">
                                    <nav aria-label="Page navigation example">
                                        <ul class="pagination justify-content-center">
                                            {% if queryset.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ queryset.previous_page_number }}" aria-label="Oldingisi">&laquo;</a>
                                            </li>
                                            {% endif %}
                                            {% for num in queryset.paginator.page_range %}
                                                {% if num == queryset.number %}
                                                    <li class="page-item active"><a class="page-link" href="#" tabindex="-1">{{ num }}</a></li>
                                                {% elif num > queryset.number|add:'-3' and num < queryset.number|add:'3' %}
                                                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if queryset.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ queryset.next_page_number }}" aria-label="Keyingisi">&raquo;</a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/quiz/quiz_list.html
{% extends 'base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">SHOP</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Kategoriya</a>
                <span class="breadcrumb-item active">Ro`yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Kategoriyalar ro`yxati</h4>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">T/r</th>
                                <th scope="col">Nomi</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for quiz in quizzes %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td> <a href="{% url 'dashboard:quiz_detail' quiz.code %}"> {{quiz.name | striptags}} </a> </td>
                                
                                <td>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded pull-right" data-toggle="modal" data-target=".bd-example-modal-lg{{forloop.counter}}">
                                        <i class="anticon anticon-edit"></i>
                                    </button>
                                    <!-- Large modal -->
                                    <div class="modal fade bd-example-modal-lg{{forloop.counter}}">
                                        <div class="modal-dialog modal-lg">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{quiz.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <form action="{% url 'dashboard:quiz_update' quiz.code %}" method="post">
                                                    {% csrf_token %}
                                                <div class="modal-body">
                                                    <input type="text" class="form-control" value="{{quiz.name}}" name="name">
                                                </div>
                                                <button type="submit" class="btn btn-primary btn-tone" >O`zgartirish</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Small modal -->
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-delete"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{quiz.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{quiz.name}} kategoriyani o`chirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'dashboard:quiz_delete' quiz.code %}">
                                                        {% csrf_token %}
                                                    <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            {% if queryset.paginator.num_pages > 1 %}
                                <div class="pagination-area">
                                    <nav aria-label="Page navigation example">
                                        <ul class="pagination justify-content-center">
                                            {% if queryset.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ queryset.previous_page_number }}" aria-label="Oldingisi">&laquo;</a>
                                            </li>
                                            {% endif %}
                                            {% for num in queryset.paginator.page_range %}
                                                {% if num == queryset.number %}
                                                    <li class="page-item active"><a class="page-link" href="#" tabindex="-1">{{ num }}</a></li>
                                                {% elif num > queryset.number|add:'-3' and num < queryset.number|add:'3' %}
                                                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if queryset.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ queryset.next_page_number }}" aria-label="Keyingisi">&raquo;</a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}