api/urls.py
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from . import views


schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
    path('quiz-detail/<str:code>', views.quiz_detail),
    path('answer-create/<str:code>', views.answer_create),
    path('log-in', views.log_in),
    path('auth/', include('rest_framework.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    path('', include('front.urls'))
]+static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)

front/urls.py
from . import views
from django.urls import path

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('quiz-detail/<str:code>/', views.quiz_detail, name='quiz_detail'),
]

front/views.py
from django.shortcuts import render, redirect
from main import models
import random


def index(request):
    quizzes = models.Quiz.objects.all()
    context = {
        'quizzes':quizzes
    }
    return render(request, 'front/index.html', context)



def quiz_detail(request, code):
  quiz = models.Quiz.objects.get(code=code)
  questions = models.Question.objects.filter(quiz=quiz)
  questions_list = list(questions)
  random.shuffle(questions_list)
  
  context = {
    'quiz': quiz,
    'questions': questions_list
    }
  if request.method == 'POST':
    answer = models.Answer.objects.create(
        quiz=quiz,
        user_name=request.POST.get('user_name'),
        phone=request.POST.get('phone'),
        email=request.POST.get('email')
    )
    for key, value in request.POST.items():
      if key.startswith('question'):
        question_id = int(key[len('question['):-len(']')])
       
        models.AnswerDetail.objects.create(
            answer=answer,
            question_id=question_id,
            user_answer_id=int(value)
        )
  
  return render(request, 'front/quiz-detail.html', context)

templates/front/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin paneli</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/logo/favicon.png' %}">

    <!-- page css -->
    <link href="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">

    <!-- Core css -->
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="{% url 'front:index' %}">
                        <img src="{% static 'images/logo/logo.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'images/logo/logo-fold.png' %}" alt="Logo">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="index.html">
                        <img src="{% static 'images/logo/logo-white.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'images/logo/logo-fold-white.png' %}" alt="Logo">
                    </a>
                </div>
            </div>    
            <!-- Header END -->


            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <ul class="side-nav-menu scrollable">
                        <li class="side-nav-header">
                            <a href="{% url 'front:index' %}">
                                <span class="title"><b>Bosh sahifa</b></span>
                            </a>
                        </li>
                        
                    </ul>
                </div>
            </div>
            <!-- Side Nav END -->

            <!-- Page Container START -->
            <div class="page-container">
                
                {% block content %}
                {% endblock %}
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0"> © 2024</p>
                        <span>
                            <a href="" class="text-gray m-r-15">Term &amp; Holatlar</a>
                            <a href="" class="text-gray">Maxfiylik &amp; Xavfsizlik</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

        </div>
    </div>

    
    <!-- Core Vendors JS -->
    <script src="{% static 'js/vendors.min.js' %}"></script>

    <!-- page js -->
    <script src="{% static 'vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/pages/dashboard-project.js' %}"></script>
    

    <!-- Core JS -->
    <script src="{% static 'js/app.min.js' %}"></script>

</body>

</html>

templates/front/index.html
{% extends 'front/base.html' %}

{% block content %}


<div class="main-content">
    
    <div class="card">
        <div class="card-body">
            <h4>Quizlar ro`yxati</h4>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">T/r</th>
                                <th scope="col">Nomi</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for quiz in quizzes %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td> <a href="{% url 'front:quiz_detail' quiz.code %}"> {{quiz.name | striptags}} </a> </td>
                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/front/quiz-detail.html
{% extends 'front/base.html' %}

{% block content %}
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Quiz</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Quizlar</a>
                <span class="breadcrumb-item active">{{ quiz.name }}</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <form id="quiz-form" action="" method="post">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label for="user_name">Full name</label>
                    <input type="text" class="form-control" id="user_name" placeholder="Full name" name="user_name" required>
                </div>
                <div class="form-group">
                    <label for="phone">Phone</label>
                    <input type="text" class="form-control" id="phone" placeholder="+998********" name="phone">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="example@gmail.com" name="email">
                </div>
                {% for question in questions %}
                <div class="container">
                    <div class="d-flex justify-content-between">
                    <h2 class="font-weight-normal m-b-10">{{ forloop.counter }}. {{ question.name | striptags }}</h2>
                    </div>
                    <div class="card-body">
                    <div class="m-t-25">
                        {% for option in question.options %}
                        <div class="radio">
                            <input id="radio{{ question.id }}_{{ option.id }}" 
                                name="question[{{ question.id }}]"  type="radio" value="{{ option.id }}">
                            <label for="radio{{ question.id }}_{{ option.id }}">{{ option.name }}</label>
                        </div>
                        {% endfor %}
                    </div>
                    </div>
                </div>
                {% endfor %}

            </div>
            <button class="btn btn-success" type="submit" data-toggle="modal" data-target="#resultModal">Yuborish</button>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="resultModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resultModalLabel">Result</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h3 id="resultText">To'g'ri javoblar soni: {{ correct }}</h3>
            </div>
        </div>
    </div>
</div>

{% endblock %}