api/urls.py
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from . import views


schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
    path('quiz-detail/<str:code>', views.quiz_detail),
    path('answer-create/<str:code>', views.answer_create),
    path('log-in', views.log_in),
    path('auth/', include('rest_framework.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    path('', include('front.urls'))
]+static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    # quiz 
    path('quiz-create/', views.quiz_create, name='quiz_create'),
    path('quiz-detail/', views.quiz_detail, name='quiz_detail'),
    path('quiz-list/', views.quiz_list, name='quiz_list'),
    path('quiz-update/<str:code>/', views.quiz_update, name='quiz_update'),
    path('quiz-detail/<str:code>/', views.quiz_detail, name='quiz_detail'),
    path('quiz-delete/<str:code>/', views.quiz_delete, name='quiz_delete'),
    # question
    path('question-create/<str:code>/', views.question_create, name='question_create'),
    path('question-detail/<str:code>/', views.question_detail, name='question_detail'),
    path('question-update/<str:code>/', views.question_update, name='question_update'),
    path('question-delete/<str:code>/', views.question_delete, name='question_delete'),
    # answer
    path('answer-list/<str:code>/', views.answer_list, name='answer_list'),
    path('answer-detail/<str:code>/', views.answer_detail, name='answer_detail'),
    path('write-excel/<str:code>/', views.write_excel, name='write_excel'),
    

    # user
    path('log-in/', views.log_in, name='log_in'),
    path('log-out/', views.log_out, name='log_out'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin paneli</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/logo/favicon.png' %}">

    <!-- page css -->
    <link href="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">

    <!-- Core css -->
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="index.html">
                        <img src="{% static 'images/logo/logo.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'images/logo/logo-fold.png' %}" alt="Logo">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="index.html">
                        <img src="{% static 'images/logo/logo-white.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'images/logo/logo-fold-white.png' %}" alt="Logo">
                    </a>'quizzes':quizzes
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav-right">
                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">
                                <div class="avatar avatar-image  m-h-10 m-r-15">
                                    <img src="{% static 'images/avatars/thumb-3.jpg' %}"  alt="">
                                </div>
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img src="{% static 'images/avatars/thumb-3.jpg' %}" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <p class="m-b-0 text-dark font-weight-semibold">Marshall Nichols</p>
                                            <p class="m-b-0 opacity-07">UI/UX Desinger</p>
                                        </div>
                                    </div>
                                </div>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                            <span class="m-l-10">Profilni tahrirlash</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-lock"></i>
                                            <span class="m-l-10">Hisob sozlamalari</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-project"></i>
                                            <span class="m-l-10">Proyektlar</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="{% url 'dashboard:log_out' %}" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Chiqish</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>    
            <!-- Header END -->


            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <ul class="side-nav-menu scrollable">
                        <li class="side-nav-header">
                            <a href="{% url 'dashboard:index' %}">
                                <span class="title">Bosh sahifa</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown open">
                            <a class="dropdown-toggle" href="javascript:void(0);">
                                <span class="icon-holder">
                                    <i class="anticon anticon-appstore"></i>
                                </span>
                                <span class="title">Tahrirlash va ro'yxatlar</span>
                                <span class="arrow">
                                    <i class="arrow-icon"></i>
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <li class="nav-item dropdown open">
                                        <a class="dropdown-toggle" href="javascript:void(0);">
                                            <span class="icon-holder">
                                                <i class="anticon anticon-ordered-list"></i>
                                            </span>
                                            <span class="title">Quizlar</span>
                                            <span class="arrow">
                                                <i class="arrow-icon"></i>
                                            </span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'dashboard:quiz_create' %}">
                                                    <i class="anticon anticon-plus-circle"></i>
                                                    Yaratish
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'dashboard:quiz_list' %}">
                                                    <span class="icon-holder">
                                                        <i class="fas fa-align-justify"></i>
                                                        Ro'yxat
                                                    </span>
                                                        
                                                </a>
                                            </li>
                                           

                                        </ul>
                                    </li>
                                </li>
                            </ul>
                        </li>
                        
                    </ul>
                </div>
            </div>
            <!-- Side Nav END -->

            <!-- Page Container START -->
            <div class="page-container">
                
                {% block content %}
                {% endblock %}
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0"> © 2024</p>
                        <span>
                            <a href="" class="text-gray m-r-15">Term &amp; Holatlar</a>
                            <a href="" class="text-gray">Maxfiylik &amp; Xavfsizlik</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

        </div>
    </div>

    
    <!-- Core Vendors JS -->
    <script src="{% static 'js/vendors.min.js' %}"></script>

    <!-- page js -->
    <script src="{% static 'vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/pages/dashboard-project.js' %}"></script>
    

    <!-- Core JS -->
    <script src="{% static 'js/app.min.js' %}"></script>

</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<!-- Content Wrapper START -->
         <div class="main-content">
            <div class="page-header no-gutters">
                <div class="d-md-flex align-items-md-center justify-content-between">
                    <div class="media m-v-10 align-items-center">
                        <div class="avatar avatar-image avatar-lg">
                            <img src="{% static 'images/avatars/thumb-3.jpg' %}" alt="">
                        </div>
                        <div class="media-body m-l-15">
                            <h4 class="m-b-0">Xush kelibsiz, Nichols!</h4>
                            <span class="text-gray">Project Manager</span>
                        </div>
                    </div>
                    <div class="d-md-flex align-items-center d-none">
                        <div class="media align-items-center m-r-40 m-v-5">
                            <div class="font-size-27">
                                <i class="text-primary anticon anticon-profile"></i>
                            </div>
                            <div class="d-flex align-items-center m-l-10">
                                <h2 class="m-b-0 m-r-5">{{quiz | length}}</h2>
                                <span class="text-gray">Quiz</span>
                            </div>
                        </div>
                        <div class="media align-items-center m-r-40 m-v-5">
                            <div class="font-size-27">
                                <i class="text-success  anticon anticon-appstore"></i>
                            </div>
                            <div class="d-flex align-items-center m-l-10">
                                <h2 class="m-b-0 m-r-5">{{questions | length}}</h2>
                                <span class="text-gray">Savollar</span>
                            </div>
                        </div>
                        <div class="media align-items-center m-v-5">
                            <div class="font-size-27">
                                <i class="text-danger anticon anticon-team"></i>
                            </div>
                            <div class="d-flex align-items-center m-l-10">
                                <h2 class="m-b-0 m-r-5"> {{users}} </h2>
                                <span class="text-gray">Foydalanuvchilar</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Wrapper END -->
{% endblock %}

templates/question-detail.html
{% extends 'base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">SHOP</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Kategoriya</a>
                <span class="breadcrumb-item active">Ro`yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Kategoriyalar ro`yxati</h4>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nom</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for q in queryset %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{q.name}}</td>
                                <td>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded pull-right" data-toggle="modal" data-target=".bd-example-modal-lg{{forloop.counter}}">
                                        <i class="anticon anticon-edit"></i>
                                    </button>
                                    <!-- Large modal -->
                                    <div class="modal fade bd-example-modal-lg{{forloop.counter}}">
                                        <div class="modal-dialog modal-lg">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{q.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <form action="#" method="post">
                                                    {% csrf_token %}
                                                <div class="modal-body">
                                                    <input type="text" class="form-control" value="{{q.name}}" name="name">
                                                </div>
                                                <button type="submit" class="btn btn-primary btn-tone" >O`zgartirish</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Small modal -->
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-delete"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{q.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{q.name}} kategoriyani o`chirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'category_delete' q.code %}">
                                                        {% csrf_token %}
                                                    <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            {% if queryset.paginator.num_pages > 1 %}
                                <div class="pagination-area">
                                    <nav aria-label="Page navigation example">
                                        <ul class="pagination justify-content-center">
                                            {% if queryset.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ queryset.previous_page_number }}" aria-label="Oldingisi">&laquo;</a>
                                            </li>
                                            {% endif %}
                                            {% for num in queryset.paginator.page_range %}
                                                {% if num == queryset.number %}
                                                    <li class="page-item active"><a class="page-link" href="#" tabindex="-1">{{ num }}</a></li>
                                                {% elif num > queryset.number|add:'-3' and num < queryset.number|add:'3' %}
                                                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if queryset.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ queryset.next_page_number }}" aria-label="Keyingisi">&raquo;</a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/quiz-create.html
{% extends 'base.html' %}

{% block content %}

                
    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">Quiz</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                    <a class="breadcrumb-item" href="#">Quiz</a>
                    <span class="breadcrumb-item active">Yaratish</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h4>Quiz yaratish</h4>
                <div class="m-t-25" style="max-width: 700px">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="inputName" class="col-sm-2 col-form-label">Nomi</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputName" placeholder="Quiz nomini kiriting" name="name" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Saqlash</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->


{% endblock %}